name: master

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'documentation/**'
      - '*.md'
      - '*.yml'
    branches:
      - master

jobs:
  linux:
    strategy:
      matrix:
        project: 
          - kotest-allure
          - kotest-javascript
          - kotest-multiplatform
          - kotest-native
          - kotest-spring-webflux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: ./${{ matrix.project }}/gradlew check

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        project: 
          - kotest-allure
          - kotest-javascript
          - kotest-multiplatform
          - kotest-native
          - kotest-spring-webflux
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Run macos tests
        run: ./${{ matrix.project }}/gradlew macosX64Test

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        project: 
          - kotest-allure
          - kotest-javascript
          - kotest-multiplatform
          - kotest-native
          - kotest-spring-webflux
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Run tests
        run: ./${{ matrix.project }}/gradlew mingwX64Test

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
